version: "3.9"
services:
  mysqldb:
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=test
    ports:
      - "3307:3306"
  app:
    depends_on:
      - mysqldb
    build: .
    env_file:
      - ./.env
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "8080:8080"
